export const STATES = {
  START: "START",
  USER_PROFILE: "USER_PROFILE",
  FRIENDSHIP_KEY: "FRIENDSHIP_KEY",
  HOW_IT_WORKS: "HOW_IT_WORKS",
  USER_FRIENDS: "USER_FRIENDS",
  FRIEND_ADD: "FRIEND_ADD",
  FRIEND_REMOVE: "FRIEND_REMOVE",
};
